server:
  port: 9011
  context-path: /user

# Swagger的访问路径
#springfox.documentation.swagger.v2.path: /api-docs


spring:
  application:
    name: challenger-smart
  jmx:
    default-domain: challenger-smart
  datasource:
    url: jdbc:mysql://10.16.10.158:3306/challenger_smart?useUnicode=true&characterEncoding=utf8
    username: smart
    password: senthink
    driver-class-name: com.mysql.jdbc.Driver
#    tomcat:
#      init-s-q-l: SET NAMES utf8mb4
#  redis:
#    host: 10.16.10.158
#    port: 6379
#    timeout: 3600
#    password:
#    database: 0
#    pool:
#      max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
#      max-idle: 8 # 连接池中的最大空闲连接
#      max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
#      min-idle: 0 # 连接池中的最小空闲连接
mybatis:
  mapper-locations:
    - classpath:mapper/*Mapper.xml
  type-aliases-package: com.example.user.domain.po

# 分页插件配置
pagehelper:
  reasonable: false
  support-methods-arguments: true
  params: count=count
  Sqlrow-bounds-with-count: true
  helper-dialect: mysql

